// web/src/components/Editor/FunctionEditor.tsx
import { useEffect, useRef } from "react";
import * as monaco from "monaco-editor/esm/vs/editor/editor.api";

import "./userWorker";

import { AutoImportTypings } from "./typesResolve";

const autoImportTypings = new AutoImportTypings();

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
  target: monaco.languages.typescript.ScriptTarget.ES2016,
  allowNonTsExtensions: true,
  moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
  module: monaco.languages.typescript.ModuleKind.CommonJS,
  noEmit: true,
  allowJs: false,
  // typeRoots: ['node_modules/@types']
});

monaco?.editor.defineTheme("lafEditorTheme", {
  base: "vs",
  inherit: true,
  rules: [],
  colors: {
    "editorLineNumber.foreground": "#aaa",
    "editorOverviewRuler.border": "#fff",
    "editor.lineHighlightBackground": "#F5F6F8",
    "scrollbarSlider.background": "#E8EAEC",
    "editorIndentGuide.activeBackground": "#ddd",
    "editorIndentGuide.background": "#eee",
  },
});

const updateModel = (path: string, value: string, editorRef: any) => {
  const newModel =
    monaco.editor.getModel(monaco.Uri.parse(path)) ||
    monaco.editor.createModel(value, "typescript", monaco.Uri.parse(path));

  if (editorRef.current?.getModel() !== newModel) {
    editorRef.current?.setModel(newModel);
  }
};

function FunctionEditor(props: {
  value: string;
  onChange: (value: string | undefined) => void;
  path: string;
}) {
  const { value, onChange, path } = props;

  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>();
  const subscriptionRef = useRef<monaco.IDisposable | undefined>(undefined);
  const monacoEl = useRef(null);

  // onChange
  useEffect(() => {
    subscriptionRef.current?.dispose();

    if (onChange) {
      subscriptionRef.current = editorRef.current?.onDidChangeModelContent((event) => {
        onChange(editorRef.current?.getValue());
      });
    }
  }, [onChange]);

  useEffect(() => {
    if (monacoEl && editorRef.current) {
      updateModel(path, value, editorRef);
    }
  }, [path, value]);

  useEffect(() => {
    if (monacoEl && !editorRef.current) {
      editorRef.current = monaco.editor.create(monacoEl.current!, {
        minimap: {
          enabled: false,
        },
        language: "typescript",
        automaticLayout: true,
        scrollbar: {
          verticalScrollbarSize: 6,
        },
        lineNumbersMinChars: 4,
        fontSize: 14,
        theme: "lafEditorTheme",
        scrollBeyondLastLine: false,
      });

      updateModel(path, value, editorRef);

      setTimeout(() => {
        autoImportTypings.loadDefaults();
      }, 10);
    }

    return () => {};
  }, [path, value]);

  return <div style={{ height: "95%" }} ref={monacoEl}></div>;
}

export default FunctionEditor;

// packages/web/src/components/FunctionEditor/index.vue
<script lang="ts" setup>
import { debounce } from 'lodash'
import * as monaco from 'monaco-editor'
import 'monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution'

import { AutoImportTypings } from './types/index'

const props = defineProps({
  modelValue: {
    type: String,
    default: '',
  },
  height: {
    type: Number,
    default: 300,
  },
  dark: {
    type: Boolean,
    default: false,
  },
  name: {
    type: String,
    default: () => {
      return `index-${Date.now()}.ts`
    },
  },
})

const emit = defineEmits(['input', 'change', 'update:modelValue'])

let editorInstance: monaco.editor.IStandaloneCodeEditor
const dom = ref()

// compiler options
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
  target: monaco.languages.typescript.ScriptTarget.ES2016,
  allowNonTsExtensions: true,
  moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
  module: monaco.languages.typescript.ModuleKind.CommonJS,
  noEmit: true,
  allowJs: false, // 此选项为 true 会影响 main 函数的类型推导
  // typeRoots: ['node_modules/@types']
})

const autoImportTypings = new AutoImportTypings()

/**
 * 当代码变化时，尝试解析是否有新 import 的依赖，并加载其类型文件
 */
const parseImports = debounce(autoImportTypings.parse, 2000, { leading: true }).bind(autoImportTypings)

function initEditor() {
  const filename = `${props.name}=${Date.now()}.ts`
  editorInstance = monaco.editor.create(dom.value, {
    lineNumbers: 'on',
    roundedSelection: true,
    scrollBeyondLastLine: false,
    theme: props.dark ? 'vs-dark' : 'vs',
    readOnly: false,
    formatOnType: true,
    fontSize: 12,
    linkedEditing: true,
    cursorBlinking: 'expand',
    smoothScrolling: true,
    renderWhitespace: 'selection',
    tabSize: 2,
    automaticLayout: true,
    autoIndent: 'keep',
    showFoldingControls: 'always',
    showDeprecated: true,
    definitionLinkOpensInPeek: false,
    model: monaco.editor.createModel(props.modelValue || '', 'typescript', monaco.Uri.parse(filename)),
  })

  editorInstance.onDidChangeModelContent((e) => {
    const value = editorInstance?.getValue()
    emit('input', value)
    emit('update:modelValue', value)
    emit('change', value)
    parseImports(getValue() || '')
  })

  // setTimeout(() => parseImports(getValue()), 0)
  parseImports(getValue())
}

function getValue() {
  return editorInstance?.getValue()
}

onMounted(() => {
  initEditor()
  autoImportTypings.loadDefaults()
})

watch(() => props.modelValue, (value) => {
  if (value !== editorInstance?.getValue())
    editorInstance.setValue(value)
})
</script>

<template>
  <div ref="dom" class="editor" />
</template>

<style lang="scss" scoped>
.editor {
  height: 100%;
  width: 100%;
}
</style>
